language: d

d:
 - dmd
 
install:
 - rm -r -f src
 
script:
 - cd gen && rdmd all.d -no-update && cd ..

after_success:
 - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
 - DESC="Automatically committed from https://github.com/sel-project/sel-utils/commit/${TRAVIS_COMMIT}"
 - git config --global user.email ${EMAIL}
 - git config --global user.name ${USER}
# html (github pages) and json
 - git clone git://${REPO_GP} gp
 - git rm -r -f gp/json
 - cp -r -f pages/. gp
 - cp -r -f json/. gp/json
 - cd gp
 - git remote
 - git add .
 - git commit -m "${MESSAGE}" -m "${DESC}"
 - git push "https://${TOKEN}@${REPO_GP}" master
# d
 - cd ..
 - git clone git://${REPO_D} d
 - git rm -r -f d/src
 - cp -r -f src/d/. d/src
 - cd d
 - git remote
 - git add .
 - git commit -m "${MESSAGE}" -m "${DESC}"
 - git push "https://${TOKEN}@${REPO_D}" master
 - git tag -a v1.0.$(<../gen/.version) -m "${DESC}"
 - git push --tags "https://${TOKEN}@${REPO_D}" master
# java
 - cd ..
 - git clone git://${REPO_JAVA} java
 - git rm -r -f java/src
 - cp -r -f src/java/. java/src/main/java
 - cd java
 - git remote
 - git add .
 - git commit -m "${MESSAGE}" -m "${DESC}"
 - git push "https://${TOKEN}@${REPO_JAVA}" master
# js
 - cd ..
 - git clone git://${REPO_JS} js
 - git rm -r -f js/src
 - cp -r -f src/js/. js/src
 - cd js
 - git remote
 - git add .
 - git commit -m "${MESSAGE}" -m "${DESC}"
 - git push "https://${TOKEN}@${REPO_JS}" master
