language: d

d:
 - dmd
 
install:
 - rm -r -f src
 
script:
 - cd gen && rdmd all.d -no-update && cd ..

after_success:
 - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
 - git clone git://${REPO_D} d
 - mv -f src/d d
 - cd d
 - git remote
 - git config user.email ${EMAIL}
 - git config user.name ${USER}
 - git add .
 - git commit -m ${MESSAGE}
 - git push "https://${TOKEN}@${REPO_D}" master
