language: d

d:
 - dmd
 
install:
 - rm -r -f src
 
script:
 - cd gen && rdmd all.d -no-update && cd ..

after_success:
 - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
 - DESC="Automatically committed from github.com/sel-project/sel-utils (${TRAVIS_COMMIT})"
 - git config --global user.email ${EMAIL}
 - git config --global user.name ${USER}
# d
 - git clone git://${REPO_D} d
 - cp -r -f src/d/ d/src
 - cd d
 - rm -r -f d
 - git remote
 - git add .
 - git commit -m "${MESSAGE}" -m "${DESC}"
 - git push "https://${TOKEN}@${REPO_D}" master
 - git tag v1.0.$(<../gen/.version)
 - git push --tags "https://${TOKEN}@${REPO_D}" master
# java
 - cd ..
 - git clone git://${REPO_JAVA} java
 - cp -r -f src/java/ java/src
 - cd java
 - rm -r -f java
 - git remote
 - git add .
 - git commit -m "${MESSAGE}" -m "${DESC}"
 - git push "https://${TOKEN}@${REPO_JAVA}" master
# TODO: js
